employee_management/config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]

  resources :managers do
    resources :employees, only: [:create, :destroy, :show]
  end

  get('/', { to: 'welcomes#index', as: 'home' })
  post('/users/search', {to: 'users#search'})
end

employee_management/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

employee_management/app/models/designation.rb
class Designation < ApplicationRecord
    validates(:title, presence: true)
end

employee_management/app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :user
  belongs_to :manager

  validates(
      :user,
      uniqueness: true
  )
end

employee_management/app/models/manager.rb
class Manager < ApplicationRecord
  belongs_to :user
  has_many :employees, dependent: :nullify

  validates(
      :user,
      uniqueness: true
  )
end

employee_management/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  belongs_to :designation

  validates :name, :dob, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  
  validates(
      :email,
      presence: true,
      uniqueness: true,
      format: VALID_EMAIL_REGEX
  )
  
end

employee_management/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    def current_user
      if session[:user_id].present?
        @current_user ||= User.find_by(id: session[:user_id]) # ifcurrent user is present then use it otherwise find from the table.
      end
    end
    helper_method(:current_user)


    def user_signed_in?
        current_user.present?
    end
      helper_method :user_signed_in?


    def authenticate_user!
        unless current_user.present?
          flash[:danger] = "You must sign in or sign up first!"
          redirect_to new_user_path
        end
    end
end

employee_management/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
end

employee_management/app/controllers/managers_controller.rb
class ManagersController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
    # before_action :find_product, only: [:show, :edit, :update, :destroy]
    # before_action :authorize_user!, only: [:edit, :update, :destroy]

    def new
        @manager = Manager.new
    end

    def create
    end

    def show
    end

    def edit
    end

    def update
    end

    def destroy
    end



    # private
    # def authorize_user!
    #     unless can?(:manage, @product)
    #       flash[:danger] = "Access Denied"
    #       redirect_to product_path(@product) # Product show page 
    #     end
    # end

end

employee_management/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end

    def create
        user = User.find_by(email: params[:session][:email])
        if user&.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "Thanks for signing in, #{user.name}!"
            redirect_to home_path
        else
            flash[:danger] = "Invalid email or password"
            redirect_to new_session_path
        end
    end

end

employee_management/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        
    end

    def search
        console.log(params[:user][:name])
        @user = User.find_by(name: params[:name])
        console.log(@user.name)
        redirect_to user_path(@user)
    end

    def show
        @user = User.find (params[:id])
    end


end

employee_management/app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
    def index
        
    end
end

employee_management/app/helpers/application_helper.rb
module ApplicationHelper
end

employee_management/app/helpers/employees_helper.rb
module EmployeesHelper
end

employee_management/app/helpers/managers_helper.rb
module ManagersHelper
end

employee_management/app/helpers/sessions_helper.rb
module SessionsHelper
end

employee_management/app/helpers/users_helper.rb
module UsersHelper
end

employee_management/app/helpers/welcomes_helper.rb
module WelcomesHelper
end

employee_management/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to( 'Home', home_path, class:"nav-link") %>
      </li>

      <% if user_signed_in? %>
      
      <li class="nav-item active">
        <%= link_to(
          'Sign Out',
          session_path,
          method: :delete,
          class: "nav-link" 
        ) %>
      </li>
    </ul>
      <%= form_tag(users_search_path, method: :post, class:"form-inline my-2 my-lg-0") do%>
      
         <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name = "name">
        <button class="btn btn-outline-success my-2 my-sm-0"  type="submit">Search</button>
      <% end %>

    <% else %>
    
      <li class="nav-item active">
        <a class="nav-link" href="<%=new_user_path%>">Sign Up</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="<%=new_session_path%>">Sign In</a>
      </li>
      </ul>
    <% end %>
    
    
  </div>
</nav>
    
    
    <% flash.each do |type, message| %>
      <div class="flash flash-<%= type %>">
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

employee_management/app/views/managers/new.html.erb
<h1> Welcome Manager </h1>

employee_management/app/views/users/show.html.erb
<h1> Employee Information </h1>
<div>
<h5><%= @user.name %></h5><br/>
<h5><%= @user.dob %></h5><br/>
<h5><%= @user.email %></h5><br/>
<h5><%= @user.designation %></h5><br/>


</div>

employee_management/app/views/welcomes/index.html.erb
<h1> Welcome </h1>